//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alek.ChatService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Conversations
    {
        public int UsersConversationsID { get; set; }
        public int UserID { get; set; }
        public int ConversationID { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User User { get; set; }
    }
}
